### PR TITLE
[Phantom] Update phantom configs

### PR DESCRIPTION
**Pull request by wjowsa**
Because of latest changes in Phantom code,  example configuration files have to be updated. 
Some not mandatory options do not have to be added to example configuration files. 
The changes are as follows: 
- remove version option - phantom will not support multiple versions 
- remove fake nat related options because they are not mandatory and set to false by default
- replace private ip address with example of public ip address in local_addr option in order not to mislead users. 
- change site_to_site option to false in examples of forwarding setup.

### CODE REVIEW

**Comment by lukbaj** [comment]
Can you explain why we need to change it in description? Is it because of recent changes to Phantom? Please describe the motivation of the change.

**Comment by kristrev** [comment]
The motivation is to simplify and clean up the configuration files and only make them contain the mandatory options, so that it is easier for a user to get started with Phantom. We discussed with Audun and currently the configuration files contains a mix of mandatory, optional and dead options :)

**Review by kristrev — APPROVED** [review]
COnfigs looks good to me.

**Comment by realmobile** [comment]
Let me know when I can read the whole guide in Nimbus and I can also review.

**Comment by lukbaj** [comment]
@kristrev Thanks for explanation. Approved.

**Review by lukbaj — APPROVED** [review]

**Review by kristrev — APPROVED** [review]

**Pull request merged**
